version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_network 

  producer:
    build: ./nodeProducer
    container_name: producer
    ports: 
      - "3000:3000"
    depends_on: 
      - rabbitmq
    networks:
      - rabbitmq_network 

  consumer: 
    build: ./nodeConsumer
    container_name: consumer
    ports: 
      - "3001:3001"
    depends_on: 
      - rabbitmq
    networks:
      - rabbitmq_network  
      
networks:
  rabbitmq_network:
    driver: bridge
