version: '3.8'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_network 

  producer:
    build: ../../nodeProducer
    container_name: producer
    ports: 
      - "3000:3000"
    depends_on: 
      - rabbitmq
    networks:
      - rabbitmq_network 

  consumer: 
    build: ../../nodeConsumer
    container_name: consumer
    ports: 
      - "3001:3001"
    depends_on: 
      - rabbitmq
    networks:
      - rabbitmq_network

  java-consumer:
    build: ../../Javaconsumer
    container_name: java-consumer
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  java-producer:
    build: ../../Javaproducer
    container_name: java-producer
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
      
networks:
  rabbitmq_network:
    driver: bridge
